# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_self_ratting', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_pwd_reset', models.BooleanField(default=False)),
            ],
        ),
    ]
