# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bid', models.CharField(max_length=10)),
                ('Bname', models.CharField(max_length=30)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Book.Categories')),
            ],
        ),
    ]
