# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0002_book_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('Aid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Aname', models.CharField(max_length=30)),
            ],
        ),
    ]
