# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0004_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('ratings', models.FloatField()),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Book.Book_List')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Book.Book_List')),
            ],
        ),
    ]
