# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0006_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Aname',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='book_list',
            name='Bname',
            field=models.CharField(max_length=70),
        ),
    ]
