# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0009_auto_20170703_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_list',
            name='id',
        ),
        migrations.AlterField(
            model_name='book_list',
            name='Bid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
