# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0010_auto_20170703_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='Bname',
            field=models.CharField(max_length=100),
        ),
    ]
