# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0012_auto_20170703_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_details',
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='Bid',
        ),
        migrations.AddField(
            model_name='book_list',
            name='price',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='book_list',
            name='rate',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.DeleteModel(
            name='Book_Details',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
