# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0013_auto_20170703_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1, max_length=100)),
                ('rate', models.IntegerField(default=1, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='book_list',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book_list',
            name='rate',
        ),
        migrations.AddField(
            model_name='book_details',
            name='Bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Book.Book_List'),
        ),
    ]
