# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0014_auto_20170703_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='book_url',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
