# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0015_book_list_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='price',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
