# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Book', '0017_auto_20170704_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='book_url',
            field=models.CharField(default='https://idreambooks.com/images/libraries_landing_page/nytimes.png', max_length=150),
        ),
    ]
